# -*- coding: utf-8 -*-
"""health_careipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OwrNYxqYyoo9ojdXxu2hK3XotrRwbSaL
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("/content/healthcare_dataset.csv")
df

df.head()

print(df.shape)

print(df.describe())

print(df.isnull().sum())

df = df.dropna()

df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], utc=True, dayfirst=True)
df['Admission_Date'].dtype

df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"], utc=True, dayfirst=True)
df['Discharge_Date'].dtype

df['Admission_Type'] = df['Admission_Type'].str.strip().str.lower()
df.head()

df["Hospital_Stays"] = df["Discharge_Date"] - df["Admission_Date"]
df

df['Hospital_Stays'] = df['Hospital_Stays'].dt.days
Hospital_Stays_Summary = df['Hospital_Stays'].describe()
print(Hospital_Stays_Summary)

Billing_Amount_Summary = df['Billing_Amount'].describe()
print(Billing_Amount_Summary)

medical_condition_counts = df['Medical_Condition'].value_counts()
print(medical_condition_counts)

medical_condition_gender_crosstab = pd.crosstab(df['Medical_Condition'], df['Gender'])
print(medical_condition_gender_crosstab)