# -*- coding: utf-8 -*-
"""healthcare 2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12TQE4e_nuGUTSax4Qcstj7Yy01ybdPT4
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/healthcare_dataset (1).csv.xls")

df.head()

df.shape

df.describe()

print(df.isnull().sum())

df = df.dropna()

df["Admission_Date"] = pd.to_datetime(df["Admission_Date"], utc=True)
df["Admission_Date"].dtype

df["Discharge_Date"] = pd.to_datetime(df["Discharge_Date"], utc=True)
df["Discharge_Date"].dtype

df["Hospital_Stays"] = (df["Discharge_Date"] - df["Admission_Date"]).dt.days
df

billing = df.groupby(["Medical_Condition", "Admission_Type"])["Billing_Amount"].sum().unstack()
billing

billing.plot(
    kind="bar",
    stacked=True,
    figsize=(10, 6)
)
plt.xlabel("Medical Condition")
plt.ylabel("Billing Amount")
plt.title("Billing Amount by Medical Condition and Insurance Provider")
plt.xticks(rotation=45)
plt.legend(title="Insurance Provider")
plt.show()

plt.figure(figsize=(10, 6))
sns.violinplot(
    x="Medical_Condition",
    y="Hospital_Stays",
    data=df,
)
plt.title("Distribution of Hospital Stays by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Hospital Stays")
plt.show()

df["Hospital_Stays"] = (df["Discharge_Date"] - df["Admission_Date"]).dt.days
df

df["Admission_Month"] = df["Admission_Date"].dt.to_period("M")


monthly_admissions = df.groupby("Admission_Month").size()
monthly_admissions

plt.figure(figsize=(10, 6))

monthly_admissions.index = monthly_admissions.index.astype(str)

monthly_admissions.plot(kind='line', marker='o')
plt.title('Monthly Admissions')
plt.xlabel('Month')
plt.ylabel('Number of Admissions')
plt.xticks(rotation=45)
plt.grid(True)
plt.show()

correlation_matrix = df[['Age', 'Hospital_Stays', 'Billing_Amount']].corr()
correlation_matrix

correlation_matrix = df[['Age', 'Hospital_Stays', 'Billing_Amount']].corr()
correlation_matrix